export const blogsSeedData = [
  {
    id: 1,
    title: "React: The A to Z Guide to Modern Web Development",
    excerpt: "A comprehensive look at React, from its core principles to advanced patterns like Hooks and Context API.",
    content: `<h2>Introduction to React</h2><p>React is a declarative, efficient, and flexible JavaScript library for building user interfaces. It was developed by Facebook and has become the most popular choice for frontend development. React allows developers to create large web applications that can change data, without reloading the page.</p><h3>Core Principles</h3><ul><li><strong>Component-Based:</strong> Build encapsulated components that manage their own state, then compose them to make complex UIs.</li><li><strong>Declarative:</strong> React makes it painless to create interactive UIs. Design simple views for each state in your application, and React will efficiently update and render just the right components when your data changes.</li><li><strong>Virtual DOM:</strong> React creates an in-memory data-structure cache which computes the changes made and then updates the browser's displayed DOM efficiently.</li></ul><h3>Advantages of React</h3><ul><li><strong>Fast Rendering:</strong> The Virtual DOM ensures high performance.</li><li><strong>SEO Friendly:</strong> With tools like Next.js, React can be rendered on the server, making it great for SEO.</li><li><strong>Large Community:</strong> Massive ecosystem of libraries, tools, and tutorials.</li><li><strong>Reusable Components:</strong> Significant reduction in development time.</li></ul><h3>Limitations of React</h3><ul><li><strong>High Pace of Development:</strong> The environment is constantly changing, which requires developers to regularly relearn new ways of doing things.</li><li><strong>JSX as a Barrier:</strong> Some developers find JSX difficult to learn at first.</li><li><strong>Only a UI Library:</strong> React is not a full-blown framework; you often need additional libraries for routing, state management, etc.</li></ul>`,
    image: "/blogs/react.png",
    date: "May 15, 2026",
    readTime: "6 min read",
    tags: ["React", "JavaScript", "Frontend"],
    category: "Frontend",
    author: { name: "Amir Ali Liaqat", role: "Full Stack Engineer" },
  },
  {
    id: 2,
    title: "Next.js Mastery: The Full-Stack React Framework",
    excerpt: "Why Next.js is the go-to framework for React developers in 2026. SSR, SSG, and ISR explained.",
    content: `<h2>What is Next.js?</h2><p>Next.js is a React framework that gives you building blocks to create web applications. By framework, we mean Next.js handles the tooling and configuration needed for React, and provides additional structure, features, and optimizations for your application.</p><h3>Key Features</h3><ul><li><strong>Server-Side Rendering (SSR):</strong> Render React components on the server for every request.</li><li><strong>Static Site Generation (SSG):</strong> Pre-render pages at build time.</li><li><strong>Incremental Static Regeneration (ISR):</strong> Update static content after you've built your site.</li><li><strong>API Routes:</strong> Easily build your backend API within the same project.</li></ul><h3>Advantages</h3><ul><li><strong>Zero Config:</strong> Automatic compilation and bundling.</li><li><strong>Performance:</strong> Built-in image optimization and code splitting.</li><li><strong>SEO:</strong> Superior SEO due to pre-rendering capabilities.</li></ul><h3>Limitations</h3><ul><li><strong>Complexity:</strong> More complex than simple React for small projects.</li><li><strong>Opinionated:</strong> Forces you into a specific project structure and routing system.</li></ul>`,
    image: "/blogs/nextjs.png",
    date: "May 15, 2026",
    readTime: "5 min read",
    tags: ["Next.js", "React", "SSR"],
    category: "Fullstack",
    author: { name: "Amir Ali Liaqat", role: "Full Stack Engineer" },
  },
  {
    id: 3,
    title: "NestJS Architecture: Building Scalable Node.js Backends",
    excerpt: "Deep dive into NestJS, the progressive Node.js framework for building efficient and reliable server-side applications.",
    content: `<h2>The Rise of NestJS</h2><p>NestJS is a framework for building efficient, scalable Node.js server-side applications. It uses progressive JavaScript, is built with and fully supports TypeScript, and combines elements of OOP, FP, and FRP.</p><h3>Why use NestJS?</h3><p>Nest provides an out-of-the-box application architecture which allows developers and teams to create highly testable, scalable, loosely coupled, and easily maintainable applications.</p><h3>Advantages</h3><ul><li><strong>TypeScript Support:</strong> First-class support for TypeScript.</li><li><strong>Modular Architecture:</strong> Encourages clean code and separation of concerns.</li><li><strong>Angular-inspired:</strong> Developers coming from Angular will feel right at home.</li></ul><h3>Limitations</h3><ul><li><strong>Steep Learning Curve:</strong> The architecture can be overwhelming for beginners.</li><li><strong>Boilerplate:</strong> Requires more boilerplate code compared to Express.</li></ul>`,
    image: "/blogs/nestjs.png",
    date: "May 15, 2026",
    readTime: "5 min read",
    tags: ["NestJS", "Node.js", "TypeScript"],
    category: "Backend",
    author: { name: "Amir Ali Liaqat", role: "Full Stack Engineer" },
  },
  {
    id: 4,
    title: "NuxtJS: The Intuitive Vue.js Framework",
    excerpt: "Explore NuxtJS and how it simplifies the development of universal Vue.js applications.",
    content: `<h2>Introduction to NuxtJS</h2><p>Nuxt is an open-source framework under MIT license that makes web development intuitive and powerful. Create high-performance and indexable web applications and websites with confidence.</p><h3>Advantages</h3><ul><li><strong>Automatic Routing:</strong> Files in the pages directory automatically become routes.</li><li><strong>SEO by Default:</strong> Built-in meta tag management and SSR.</li><li><strong>Modular Ecosystem:</strong> Hundreds of modules for PWA, Axios, etc.</li></ul><h3>Limitations</h3><ul><li><strong>Vue-Only:</strong> You are locked into the Vue ecosystem.</li><li><strong>Documentation:</strong> While good, it sometimes lags behind the rapid updates of Nuxt 3.</li></ul>`,
    image: "/blogs/nuxtjs.png",
    date: "May 15, 2026",
    readTime: "4 min read",
    tags: ["NuxtJS", "Vue.js", "SSR"],
    category: "Frontend",
    author: { name: "Amir Ali Liaqat", role: "Full Stack Engineer" },
  },
  {
    id: 5,
    title: "GraphQL & Apollo: The Future of Data Fetching",
    excerpt: "How GraphQL and Apollo Client/Server are changing the way we interact with APIs.",
    content: `<h2>Why GraphQL?</h2><p>GraphQL is a query language for APIs and a runtime for fulfilling those queries with your existing data. GraphQL provides a complete and understandable description of the data in your API, gives clients the power to ask for exactly what they need and nothing more.</p><h3>Apollo Client & Server</h3><p>Apollo is a platform for building a supergraph, a unified network of all your data, services, and digital capabilities that connects to your application clients.</p><h3>Advantages</h3><ul><li><strong>No Over-fetching:</strong> Get exactly what you need.</li><li><strong>Strongly Typed:</strong> Schema-based development ensures data consistency.</li><li><strong>Real-time with Subscriptions:</strong> Built-in support for WebSockets.</li></ul><h3>Limitations</h3><ul><li><strong>Caching Complexity:</strong> Client-side caching can be tricky to implement correctly.</li><li><strong>Security:</strong> Vulnerable to deeply nested queries (requires complexity limits).</li></ul>`,
    image: "/blogs/graphql.png",
    date: "May 15, 2026",
    readTime: "5 min read",
    tags: ["GraphQL", "Apollo", "API"],
    category: "Backend",
    author: { name: "Amir Ali Liaqat", role: "Full Stack Engineer" },
  },
  {
    id: 6,
    title: "AWS vs DigitalOcean: Choosing Your Cloud Provider",
    excerpt: "A detailed comparison between the giant AWS and the developer-friendly DigitalOcean.",
    content: `<h2>The Cloud Landscape</h2><p>Choosing a cloud provider depends on your project size, budget, and technical expertise.</p><h3>AWS (Amazon Web Services)</h3><p>AWS is the most comprehensive and broadly adopted cloud platform, offering over 200 fully featured services from data centers globally.</p><ul><li><strong>Advantages:</strong> Unmatched scale, huge range of services, industry standard.</li><li><strong>Limitations:</strong> Extremely complex, can be very expensive if not managed properly.</li></ul><h3>DigitalOcean</h3><p>DigitalOcean is a cloud infrastructure provider focused on simplifying web infrastructure for software developers.</p><ul><li><strong>Advantages:</strong> Simple UI, predictable pricing, great for small to medium apps.</li><li><strong>Limitations:</strong> Fewer advanced services compared to AWS.</li></ul>`,
    image: "/blogs/cloud.png",
    date: "May 15, 2026",
    readTime: "5 min read",
    tags: ["AWS", "DigitalOcean", "Cloud"],
    category: "DevOps",
    author: { name: "Amir Ali Liaqat", role: "Full Stack Engineer" },
  },
  {
    id: 7,
    title: "Tailwind CSS: The Utility-First Revolution",
    excerpt: "Why Tailwind CSS is dominating modern web design and how to use it effectively.",
    content: `<h2>The Utility-First Approach</h2><p>Tailwind CSS is a utility-first CSS framework for rapidly building custom user interfaces. Instead of pre-designed components, it provides low-level utility classes that let you build completely custom designs.</p><h3>Advantages</h3><ul><li><strong>Speed:</strong> Build complex UIs without leaving your HTML.</li><li><strong>Consistency:</strong> Uses a predefined design system (colors, spacing, etc.).</li><li><strong>Performance:</strong> Unused CSS is purged in production, resulting in tiny bundles.</li></ul><h3>Limitations</h3><ul><li><strong>Class Soup:</strong> HTML files can become cluttered with many classes.</li><li><strong>Learning Curve:</strong> You need to learn the utility names.</li></ul>`,
    image: "/blogs/tailwind.png",
    date: "May 15, 2026",
    readTime: "4 min read",
    tags: ["Tailwind CSS", "CSS", "Frontend"],
    category: "Frontend",
    author: { name: "Amir Ali Liaqat", role: "Full Stack Engineer" },
  },
  {
    id: 8,
    title: "MUI vs Shadcn UI: The Ultimate Showdown",
    excerpt: "An A to Z comparison between the two most popular React UI libraries.",
    content: `<h2>Choosing Your UI Foundation</h2><p>MUI and Shadcn represent two different philosophies in UI development.</p><h3>MUI (Material UI)</h3><p>A comprehensive library of components that implement Google's Material Design.</p><ul><li><strong>Advantages:</strong> Huge component library, battle-tested, great documentation.</li><li><strong>Limitations:</strong> Hard to customize outside Material Design, heavy bundle size.</li></ul><h3>Shadcn UI</h3><p>A collection of re-usable components that you can copy and paste into your apps. Built on Radix UI and Tailwind CSS.</p><ul><li><strong>Advantages:</strong> Full control over code, tiny bundle (you only add what you use), looks modern.</li><li><strong>Limitations:</strong> You own the code (more maintenance), fewer complex components compared to MUI.</li></ul>`,
    image: "/blogs/mui-vs-shadcn.png",
    date: "May 15, 2026",
    readTime: "5 min read",
    tags: ["MUI", "Shadcn", "UI Libraries"],
    category: "Frontend",
    author: { name: "Amir Ali Liaqat", role: "Full Stack Engineer" },
  },
  {
    id: 9,
    title: "The AI Revolution: Cursor, Copilot, and Claude",
    excerpt: "How AI tools are transforming software engineering. Comparing Cursor AI, GitHub Copilot, and Claude.",
    content: `<h2>The New Developer Workflow</h2><p>AI is no longer a luxury; it's a necessity for modern developers.</p><h3>Cursor AI</h3><p>The AI-native code editor. It's a fork of VS Code that integrates AI deeply into the editing experience.</p><ul><li><strong>Advantages:</strong> Context-aware (knows your whole codebase), fast, features like "Composer" for multi-file edits.</li><li><strong>Limitations:</strong> Subscription cost, relatively new.</li></ul><h3>GitHub Copilot</h3><p>The pioneer of AI coding assistants. Integrated into most IDEs.</p><ul><li><strong>Advantages:</strong> Reliable, massive training data, integrated with GitHub ecosystem.</li><li><strong>Limitations:</strong> Sometimes lacks deep codebase context compared to Cursor.</li></ul><h3>Claude (Anthropic)</h3><p>Large language model known for high-quality reasoning and coding abilities.</p><ul><li><strong>Advantages:</strong> Exceptional at explaining complex logic and refactoring.</li><li><strong>Limitations:</strong> Not an IDE extension (though tools like Cursor use it).</li></ul><h2>Creating Copilot Custom Agents</h2><p>Custom agents allow you to tailor Copilot's behavior to your specific project needs.</p>`,
    image: "/blogs/ai-tools.png",
    date: "May 15, 2026",
    readTime: "6 min read",
    tags: ["AI", "Copilot", "Claude", "Cursor"],
    category: "Tools",
    author: { name: "Amir Ali Liaqat", role: "Full Stack Engineer" },
  },
];
