export const projectsSeedData = [
  {
    name: "Designs To Deploy Agency Platform",
    description: "Official software agency portfolio and digital service portal built for Designs To Deploy.",
    tags: [{ name: "react", color: "blue-text-gradient" }, { name: "node", color: "green-text-gradient" }, { name: "mongodb", color: "pink-text-gradient" }],
    image: "/assets/company/designstodeploy-banner.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "https://www.designstodeploy.dev/",
    category: "MERN",
  },
  {
    name: "ByteBunch Software House",
    description: "Company portfolio website built for ByteBunch showcasing services, projects, and client testimonials.",
    tags: [{ name: "wordpress", color: "blue-text-gradient" }, { name: "elementor", color: "green-text-gradient" }, { name: "php", color: "pink-text-gradient" }],
    image: "/assets/projects/bytebunch.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "https://bytebunch.com/",
    category: "WordPress",
  },
  {
    name: "DevBrains Software House",
    description: "Official agency site for DevBrains software house with dynamic project portfolios.",
    tags: [{ name: "wordpress", color: "blue-text-gradient" }, { name: "custom-css", color: "green-text-gradient" }],
    image: "/assets/projects/devbrains.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "https://devbrains.co/",
    category: "WordPress",
  },
  {
    name: "Plantify MERN App",
    description: "Full-stack plant store e-commerce application with dynamic cart, checkout, and admin portal.",
    tags: [{ name: "react", color: "blue-text-gradient" }, { name: "mongodb", color: "green-text-gradient" }, { name: "express", color: "pink-text-gradient" }],
    image: "/assets/projects/plantify.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "https://plantify.dev/",
    category: "MERN",
  },
  {
    name: "Byte Ki Duniya",
    description: "Educational blogging platform delivering byte-sized technology articles and tutorials.",
    tags: [{ name: "wordpress", color: "blue-text-gradient" }, { name: "php", color: "green-text-gradient" }],
    image: "/assets/projects/byteKiDuniya.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "WordPress",
  },
  {
    name: "Mehar Herbals",
    description: "E-commerce platform for herbal and organic products with full WooCommerce integration.",
    tags: [{ name: "wordpress", color: "blue-text-gradient" }, { name: "woocommerce", color: "green-text-gradient" }],
    image: "/assets/projects/meharHerbals.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "WordPress",
  },
  {
    name: "Warraich Traders",
    description: "Business landing page and product catalog for a local trading company.",
    tags: [{ name: "wordpress", color: "blue-text-gradient" }, { name: "elementor", color: "green-text-gradient" }],
    image: "/assets/projects/warraichTraders.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "WordPress",
  },
  {
    name: "Waveslines",
    description: "Creative agency website with stunning animations and modern portfolio layouts.",
    tags: [{ name: "wordpress", color: "blue-text-gradient" }, { name: "custom-css", color: "green-text-gradient" }],
    image: "/assets/projects/waveslines.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "WordPress",
  },
  {
    name: "Cache Store",
    description: "Online digital products marketplace with secure payment gateway integration.",
    tags: [{ name: "react", color: "blue-text-gradient" }, { name: "node", color: "green-text-gradient" }],
    image: "/assets/projects/cacheStore.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "MERN",
  },
  {
    name: "Richmond Institute",
    description: "Educational institute website with course catalog, enrollment system, and event management.",
    tags: [{ name: "wordpress", color: "blue-text-gradient" }, { name: "elementor", color: "green-text-gradient" }],
    image: "/assets/projects/richmondInstitute.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "WordPress",
  },
  {
    name: "UMS - University Management System",
    description: "Full-featured university management system handling students, faculty, courses, and attendance.",
    tags: [{ name: "react", color: "blue-text-gradient" }, { name: "node", color: "green-text-gradient" }, { name: "mongodb", color: "pink-text-gradient" }],
    image: "/assets/projects/ums.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "MERN",
  },
  {
    name: "Barber Shop",
    description: "Modern barbershop appointment booking website with gallery and service pricing.",
    tags: [{ name: "html", color: "blue-text-gradient" }, { name: "css", color: "green-text-gradient" }, { name: "javascript", color: "pink-text-gradient" }],
    image: "/assets/projects/barberShop.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "MERN",
  },
  {
    name: "All In One Media",
    description: "Multi-service digital media agency website with portfolio and client dashboard.",
    tags: [{ name: "wordpress", color: "blue-text-gradient" }, { name: "elementor", color: "green-text-gradient" }],
    image: "/assets/projects/allInOneMedia.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "WordPress",
  },
  {
    name: "Coffee Shop",
    description: "Elegant coffee shop website with online menu, ordering system, and location finder.",
    tags: [{ name: "html", color: "blue-text-gradient" }, { name: "css", color: "green-text-gradient" }, { name: "javascript", color: "pink-text-gradient" }],
    image: "/assets/projects/coffeeShop.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "MERN",
  },
  {
    name: "Soar Task Manager",
    description: "Task management application with drag-and-drop boards, deadlines, and team collaboration.",
    tags: [{ name: "react", color: "blue-text-gradient" }, { name: "firebase", color: "green-text-gradient" }],
    image: "/assets/projects/soarTask.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "MERN",
  },
  {
    name: "Sports Arena",
    description: "Sports equipment e-commerce store with product filtering and checkout flow.",
    tags: [{ name: "react", color: "blue-text-gradient" }, { name: "node", color: "green-text-gradient" }],
    image: "/assets/projects/sportsArena.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "MERN",
  },
  {
    name: "MCCLG - College Website",
    description: "Official college website with departments, faculty, admissions, and event management.",
    tags: [{ name: "wordpress", color: "blue-text-gradient" }, { name: "php", color: "green-text-gradient" }],
    image: "/assets/projects/mcclg.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "WordPress",
  },
  {
    name: "Fixonic",
    description: "Device repair service booking platform with real-time tracking and technician management.",
    tags: [{ name: "react", color: "blue-text-gradient" }, { name: "node", color: "green-text-gradient" }, { name: "mongodb", color: "pink-text-gradient" }],
    image: "/assets/projects/fixonic.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "MERN",
  },
  {
    name: "NexKind",
    description: "AI-powered kindness platform connecting volunteers with community service opportunities.",
    tags: [{ name: "next", color: "blue-text-gradient" }, { name: "typescript", color: "green-text-gradient" }],
    image: "/assets/projects/nexkind.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "MERN",
  },
  {
    name: "Campus Core",
    description: "Comprehensive campus management system for universities with role-based access control.",
    tags: [{ name: "react", color: "blue-text-gradient" }, { name: "express", color: "green-text-gradient" }, { name: "mongodb", color: "pink-text-gradient" }],
    image: "/assets/projects/campusCore.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "MERN",
  },
  {
    name: "Campus Hub",
    description: "Student social platform for campus events, clubs, and academic collaboration.",
    tags: [{ name: "react", color: "blue-text-gradient" }, { name: "node", color: "green-text-gradient" }],
    image: "/assets/projects/campusHub.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "MERN",
  },
  {
    name: "PrepMaster",
    description: "Exam preparation platform with quizzes, flashcards, and progress tracking.",
    tags: [{ name: "react", color: "blue-text-gradient" }, { name: "mongodb", color: "green-text-gradient" }],
    image: "/assets/projects/prepmaster.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "MERN",
  },
  {
    name: "DevUtils",
    description: "Collection of developer utility tools including JSON formatter, color picker, and code converter.",
    tags: [{ name: "react", color: "blue-text-gradient" }, { name: "typescript", color: "green-text-gradient" }],
    image: "/assets/projects/devutils.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "Mobile",
  },
  {
    name: "Splentra",
    description: "Premium fashion e-commerce store with product catalog, wishlists, and dynamic filtering.",
    tags: [{ name: "next", color: "blue-text-gradient" }, { name: "stripe", color: "green-text-gradient" }],
    image: "/assets/projects/splentra.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "Mobile",
  },
  {
    name: "DengueGuard",
    description: "Public health awareness app for dengue prevention with location-based alerts and reporting.",
    tags: [{ name: "react-native", color: "blue-text-gradient" }, { name: "firebase", color: "green-text-gradient" }],
    image: "/assets/projects/dengueguard.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "Mobile",
  },
  {
    name: "Plantify Mobile App",
    description: "Cross-platform mobile companion app for the Plantify plant store with push notifications.",
    tags: [{ name: "react-native", color: "blue-text-gradient" }, { name: "expo", color: "green-text-gradient" }],
    image: "/assets/projects/plantifyApp.png",
    source_code_link: "https://github.com/AmirAliLiaqat",
    live_link: "#",
    category: "Mobile",
  },
];
